apiVersion: 1
datasources:
  - name: Loki
    type: loki
    url: http://loki:3100  # Loki 的服务地址
    access: proxy
    isDefault: true
    jsonData:
      maxLines: 1000
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prom:9090
    isDefault: false