apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: observability
spec:
  selector:
    app: tempo    # 👈 这个要和 Deployment 里的 labels 对应
  ports:
    - name: grpc
      port: 4317
      targetPort: 4317
    - name: http
      port: 4318
      targetPort: 4318
    - name: query
      port: 3200
      targetPort: 3200
  type: ClusterIP   # 默认是集群内部访问，如果你想外网访问可以改成 LoadBalancer