apiVersion: v1
kind: Service
metadata:
  name: my-kotlin-app
  namespace: demo
  labels:
    app: my-kotlin-app
spec:
  selector:
    app: my-kotlin-app
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP