global:
  resolve_timeout: 5m

route:
  receiver: "email"
  group_by: ["alertname"]
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h

receivers:
  - name: "email"
    email_configs:
      - to: "$ALERTMANAGER_TO_EMAIL"
        from: "$ALERTMANAGER_AUTH_USERNAME"
        smarthost: "smtp.gmail.com:587"
        auth_username: "$ALERTMANAGER_AUTH_USERNAME"
        auth_password: "$ALERTMANAGER_AUTH_PASSWORD"
        require_tls: true